=== 09abhishek/XML-XSD-Validation/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://dev.atechlab.net/Patient"
	xmlns:tns="http://dev.atechlab.net/Patient" 
	elementFormDefault="qualified">


	<element name="patient" type="tns:Patient" />

	<complexType name="Patient">
		<sequence>
			
			<element name="name" type="tns:String15Chars" />
			<element name="age" type="int" />
			<element name="dob" type="date" />
			<element name="email" type="string" maxOccurs="unbounded"/>
			<element name="gender" type="tns:Gender" />
			<element name="mobile" type="string" />
			<element name="phone" type="string"  minOccurs="0"/>
			<element name="payment" type="tns:PaymentType" />
		</sequence>
		
		<attribute name="id" type="tns:ID"/>
	</complexType>

	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int"></element>
			<element name="insurance" type="tns:Insurance"></element>
		</choice>
	</complexType>
	
	<complexType name="Insurance">
	<all>
	<element name="provider" type="string"></element>
	<element name="limit" type="int"></element>
	</all>
	</complexType>

	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="String15Chars">
		<restriction base="string">
			<maxLength value="15"></maxLength>
		</restriction>
	</simpleType>

	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>

	</simpleType>


</schema>

=== 09abhishek/XML-XSD-Validation/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://dev.atechlab.net/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dev.atechlab.net/Patient Patient.xsd ">
	
	<tns:id>1</tns:id>
	<tns:name>Abhishek</tns:name>
	<tns:age>24</tns:age>
	<tns:dob>2001-01-01</tns:dob>
	<tns:email>abhi_09@live.com</tns:email>
	<tns:gender>M</tns:gender>
	<tns:phone>9031203057</tns:phone>

</tns:patient>

=== 09abhishek/XML-XSD-Validation/kuhu.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://dev.atechlab.net/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dev.atechlab.net/Patient Patient.xsd" 
	id="123">
	<tns:name>Kuhu</tns:name>
	<tns:age>0</tns:age>
	<tns:dob>2001-01-01</tns:dob>
	<tns:email>tns:email</tns:email>
	<tns:gender>F</tns:gender>
	<tns:mobile>tns:phone</tns:mobile>
	<tns:phone>tns:phone</tns:phone>
	<tns:payment>
		<tns:insurance>
			<tns:provider> Blue Cross</tns:provider>
			<tns:limit> 3000</tns:limit>
		</tns:insurance>
	</tns:payment>
</tns:patient>
